//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEGETFOODS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public int NewsID { get; set; }
        public Nullable<int> NewsCateID { get; set; }
        public string NewsTitle { get; set; }
        public string NewsImages { get; set; }
        public string NewsSummary { get; set; }
        public string NewsBody { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual NEWSCATEGORy NEWSCATEGORy { get; set; }
    }
}
