//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEGETFOODS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDER_DETAIL = new HashSet<ORDER_DETAIL>();
        }
    
        public int OrderID { get; set; }
        public string OrderUserCode { get; set; }
        public string OrderShipAddress { get; set; }
        public string OrderPhone { get; set; }
        public Nullable<double> OrderShippingFee { get; set; }
        public string OrderShippingNote { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
        public string OrderEmail { get; set; }
        public Nullable<int> OrderPayMethod { get; set; }
        public Nullable<int> OrderTotal { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string OrderCode { get; set; }
        public string OrderFullname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL { get; set; }
        public virtual USER USER { get; set; }
    }
}
