//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEGETFOODS
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.ORDERS = new HashSet<ORDER>();
            this.SHOPPING_SESSIONS = new HashSet<SHOPPING_SESSIONS>();
            this.USER_PERMISSION = new HashSet<USER_PERMISSION>();
        }
    
        public string UserCode { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserFullName { get; set; }
        public Nullable<byte> UserEmailVerified { get; set; }
        public Nullable<System.DateTime> UserRegistrationDate { get; set; }
        public string UserVerifiactionCode { get; set; }
        public string UserAvatar { get; set; }
        public string UserPhone { get; set; }
        public string UserAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOPPING_SESSIONS> SHOPPING_SESSIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_PERMISSION> USER_PERMISSION { get; set; }
    }
}
